apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: App1
    type: Front-end

spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
