apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "update"]
    resourceNames: ["blue", "orange"]

  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]
