apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
